### ISSUE TITLE
Hostname doesn't match

### ISSUE THREAD

**Issue by galouzis** [Benny-/Yahoo-ticker-symbol-downloader#12]
I'm getting the following Traceback when I run the script

`Traceback (most recent call last):
  File "c:/Python27/Scripts/YahooTickerDownloader.py", line 144, in <module>
    main()
  File "c:/Python27/Scripts/YahooTickerDownloader.py", line 101, in main
    downloadEverything(downloader, tickerType, args.insecure)
  File "c:/Python27/Scripts/YahooTickerDownloader.py", line 46, in downloadEverything
    symbols = downloader.nextRequest(insecure)
  File "c:\python27\lib\site-packages\ytd\SymbolDownloader.py", line 88, in nextRequest
    html = self._fetchHtml(insecure)
  File "c:\python27\lib\site-packages\ytd\SymbolDownloader.py", line 40, in _fetchHtml
    resp = self.rsession.send(req)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'finance.yahoo.com' doesn't match u'www.yahoo.com'`

I'm not sure why it tries to match `finance.yahoo.com` with `u'www.yahoo.com'`. It obviously shouldn't match and I haven't been able to debug it.

**Comment by Benny-** [comment]
Could not reproduce. Can you verify you still have this problem?

**Comment by Benny-** [comment]
What happens when you use the insecure (-i) flag?
