### ISSUE TITLE
Downloading list of stocks failed

### ISSUE THREAD

**Issue by hatala91** [Benny-/Yahoo-ticker-symbol-downloader#14]
Downloading a list of stocks using the package in Python 3.3 under Windows 7 failed with the following stack trace (same result with secure and insecure connection):

Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.10.0-py3.3.egg\requests\packages\urllib3\connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python33\lib\site-packages\requests-2.10.0-py3.3.egg\requests\packages\urllib3\util\connection.py", line 91, in create_connection
    raise err
  File "C:\Python33\lib\site-packages\requests-2.10.0-py3.3.egg\requests\packages\urllib3\util\connection.py", line 81, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Pinging finance.yahoo.com does not raise any issues though!

**Comment by Benny-** [comment]
Thank you for your report. This will be investigated. There is no ETA yet.

**Comment by Benny-** [comment]
@hatala91 can you tell me how you installed the software on Windows

**Comment by hatala91** [comment]
Sure, I downloaded your package extracted it somewhere opened a command line and wrote

> python setup.py install

**Comment by Benny-** [comment]
It was not possible to reproduce this bug in windows 10.
