### ISSUE TITLE
Excel Export failed: row index (65536) not an int in range(65536)

### ISSUE THREAD

**Issue by Benny-** [Benny-/Yahoo-ticker-symbol-downloader#29]
Trace:
```
../YahooTickerDownloader.py bond -e
Exporting pickle file
Checking if we can resume a old download session
Downloader found on disk, resuming
Exporting Bond symbols
Traceback (most recent call last):
  File "../YahooTickerDownloader.py", line 161, in <module>
    main()
  File "../YahooTickerDownloader.py", line 158, in main
    f.write(data.xls)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/formats/_xls.py", line 44, in export_set
    dset_sheet(dataset, ws)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/formats/_xls.py", line 133, in dset_sheet
    ws.write(i, j, col)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/packages/xlwt3/Worksheet.py", line 1002, in write
    self.row(r).write(c, label, style)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/packages/xlwt3/Worksheet.py", line 1047, in row
    self.__rows[indx] = self.Row(indx, self)
  File "/home/benny/Private/Magic/Market/Yahoo-ticker-symbol-downloader/py3env/lib/python3.5/site-packages/tablib/packages/xlwt3/Row.py", line 40, in __init__
    raise ValueError("row index (%r) not an int in range(65536)" % rowx)
ValueError: row index (65536) not an int in range(65536)
```

**Comment by Benny-** [comment]
I am downgrading this to a feature request. If someone really needs it let me known in this issue. It will take some effort to make it  work again and this will only happen if someone requests it.
