### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Fl0tich** [Benny-/Yahoo-ticker-symbol-downloader#30]
I have tried to download the stocks symbol and the currency but i am getting this error. It seems that the url adresss change.

Traceback (most recent call last):
  File "C:\Users\myname\AppData\Local\Programs\Python\Python35\Scripts\YahooTickerDownloader.py", line 161, in <module>
    main()
  File "C:\Users\myname\AppData\Local\Programs\Python\Python35\Scripts\YahooTickerDownloader.py", line 111, in main
    downloadEverything(downloader, tickerType, args.insecure, args.sleep, args.pandantic)
  File "C:\Users\myname\AppData\Local\Programs\Python\Python35\Scripts\YahooTickerDownloader.py", line 50, in downloadEverything
    symbols = downloader.nextRequest(insecure, pandantic)
  File "c:\users\myname\appdata\local\programs\python\python35\lib\site-packages\ytd\SymbolDownloader.py", line 113, in nextRequest
    html = self._fetchHtml(insecure)
  File "c:\users\myname\appdata\local\programs\python\python35\lib\site-packages\ytd\SymbolDownloader.py", line 56, in _fetchHtml
    resp.raise_for_status()
  File "c:\users\myname\appdata\local\programs\python\python35\lib\site-packages\requests\models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://finance.yahoo.com/lookup/C?m=ALL&s=a&t=C&bypass=true&b=0

**Comment by Benny-** [comment]
I have confirmed this.

**Comment by Benny-** [comment]
I don't see a way to move to next page in the new Yahoo user interface. I guess this is the end for this web scraper. It was a fun project while it lasted.

**Comment by Benny-** [comment]
You can get old collected data here: https://bennyjacobs.nl/market/

Please leave a comment if anyone finds another data source.

**Comment by Benny-** [comment]
It is not over yet. I just found https://finance.yahoo.com/lookup/stocks?s=a&b=0 This will do nicely.
