### ISSUE TITLE
download stock info error

### ISSUE THREAD

**Issue by martin2350** [Benny-/Yahoo-ticker-symbol-downloader#37]
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\YahooTickerDownloader.py", line 161, in <module>
    main()
  File "D:\Anaconda3\Scripts\YahooTickerDownloader.py", line 111, in main
    downloadEverything(downloader, tickerType, args.insecure, args.sleep, args.p
andantic)
  File "D:\Anaconda3\Scripts\YahooTickerDownloader.py", line 50, in downloadEver
ything
    symbols = downloader.nextRequest(insecure, pandantic)
  File "D:\Anaconda3\lib\site-packages\ytd\SymbolDownloader.py", line 113, in ne
xtRequest
    html = self._fetchHtml(insecure)
  File "D:\Anaconda3\lib\site-packages\ytd\SymbolDownloader.py", line 56, in _fe
tchHtml
    resp.raise_for_status()
  File "D:\Anaconda3\lib\site-packages\requests\models.py", line 893, in raise_f
or_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://fina
nce.yahoo.com/lookup/E?s=a&t=E&m=ALL&b=0&bypass=true

**Comment by Benny-** [comment]
You are using a old version of the software. Can you update it?

**Comment by Benny-** [comment]
Please let me know and close this issue if the latest version solves the problem you are having.

**Comment by Benny-** [comment]
I also wonder where you got the old version from. Where did you find it? I will have to notify whoever it is distributing it to update to the latest version.

**Comment by martin2350** [comment]
yes!! That's it! Sorry for not reply in time and Thanks~
